---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-tools
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dns-tools
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dns-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-tools
subjects:
- kind: ServiceAccount
  name: dns-tools

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dns-tools
  name: dns-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-tools
  template:
    metadata:
      labels:
        app: dns-tools
    spec:
      serviceAccountName: dns-tools
      containers:
        - name: tools
          image: dns-tools
          imagePullPolicy: Never
          args: ["gip", "--nilfire"]
          envFrom:
            - secretRef:
                name: dns-tools
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"